=== Horazon1985/MathTool/src/mathtool/config/configXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mathToolConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fontSizeGraphic" type="xs:string"/>
                <xs:element name="fontSizeText" type="xs:string"/>
                <xs:element name="language" type="xs:string"/>
                <xs:element name="mode" type="xs:string"/>
                <xs:element name="screenWidth" type="xs:string"/>
                <xs:element name="screenHeight" type="xs:string"/>
                <xs:element name="optionAlgebraicRelations" type="xs:string"/>
                <xs:element name="optionFunctionalRelations" type="xs:string"/>
                <xs:element name="optionExpandAndCollectIfShorter" type="xs:string"/>
                <xs:element name="optionFactorizeDropDown" type="xs:string"/>
                <xs:element name="optionLogarithmsDropDown" type="xs:string"/>
                <xs:element name="timeoutComputation" type="xs:string"/>
                <xs:element name="timeoutAlgorithm" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Horazon1985/MathTool/src/mathtool/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<mathToolConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configXSD.xsd">
    <fontSizeGraphic>20</fontSizeGraphic>
    <fontSizeText>15</fontSizeText>
    <language>DE</language>
    <mode>GRAPHIC</mode>
    <screenWidth>1200</screenWidth>
    <screenHeight>670</screenHeight>
    <optionAlgebraicRelations>true</optionAlgebraicRelations>
    <optionFunctionalRelations>true</optionFunctionalRelations>
    <optionExpandAndCollectIfShorter>true</optionExpandAndCollectIfShorter>
    <optionFactorizeDropDown>factorize</optionFactorizeDropDown>
    <optionLogarithmsDropDown>collect</optionLogarithmsDropDown>
    <timeoutComputation>120</timeoutComputation>
    <timeoutAlgorithm>300</timeoutAlgorithm>
</mathToolConfig>
