=== Horazon1985/MathTool/src/mathtool/session/MathToolSessionXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mathToolSession">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="definedVars">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="variable" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="varname" type="xs:string"/>
										<xs:element name="value" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="definedFunctions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="function" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="functionname" type="xs:string"/>
										<xs:sequence>
											<xs:element name="arguments">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="varname" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:element name="functionterm" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Horazon1985/MathTool/src/mathtool/session/MathToolSampleSession.xml
<?xml version="1.0" encoding="UTF-8"?>
<mathToolSession xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MathToolSessionXSD.xsd">
    <definedVars>
        <variable>
            <varname>x</varname>
            <value>5</value>
        </variable>
        <variable>
            <varname>y</varname>
            <value>3+sin(1)</value>
        </variable>
        <variable>
            <varname>z</varname>
            <value>5</value>
        </variable>
    </definedVars>
    <definedFunctions>
        <function>
            <functionname>f</functionname>
            <arguments>
                <varname>x</varname>
                <varname>y</varname>
            </arguments>
            <functionterm>x+y^2</functionterm>
        </function>
        <function>
            <functionname>g</functionname>
            <arguments>
                <varname>u</varname>
            </arguments>
            <functionterm>3*sin(u)</functionterm>
        </function>
    </definedFunctions>
</mathToolSession>
